### ISSUE TITLE
Epic: Support LTA DataMall

### ISSUE THREAD

**Issue by achrinza** [apprexp/govsg2oas#2]
- [ ] Bus Arrival
- [ ] Bus Services
- [ ] Bus Routes
- [ ] Bus Stops
- [ ] Passenger Volume by Bus Stops
- [ ] Passenger Volume by Origin Destination Bus Stops
- [ ] Passenger Volume by Origin Destination Train Stations
- [ ] Taxi Availability
- [ ] Train Service Alerts
- [ ] Carpark Availability
- [ ] ERP Rates
- [ ] Estimated Travel Times
- [ ] Faulty Traffic Lights
- [ ] Road Openings
- [ ] Road Works
- [ ] Traffic Images
- [ ] Traffic Incidents
- [ ] Traffic Speed Bands
- [ ] VMS / EMAS
- [ ] Bicycle Parking
